from .process_logs import merge_files 
from .validation import validate_df
from .macro_plot import plot_graphs, plot_comparison
from .tables import make_table

def merge_and_validate(input_path):
    """
    Groups and merges all files under intput_path that were 
    generated by the benchmarks, furthermore, the merged file is validated
    against simple rules defined in validate_df file.

    Input: input_path -> a folder

    Output: the merged dataframe, in case of the validation being unsucessfull,
    an error is raised and the process is exited.
    """
    df1 = merge_files(input_path)
    print(df1.head())

    validation_errors = validate_df(df1)
    if validation_errors:
        for err in validation_errors:
            print(err)
        print(f"Finished with {len(validation_errors)} errors")
        sys.exit(1)
    return df1
